FROM node:22.3

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Temporarily rename .env.development to .env.production for build
COPY .env.development .env.production  

RUN npm run build

EXPOSE 3000
CMD ["npm", "start"]
