name: Docker Image CI - develop

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # SSH into your server and deploy
      - name: Injection .env
        run: |
          cat > .env.production << EOF
          NEXT_PUBLIC_API_URL=http://192.168.68.161:8081
          SSL_CERTIFICATE=${{ secrets.ISF_CERTIFICATE }}
          CERTIFICATE_KEY=${{ secrets.ISF_SERVER_KEY }}
          EOF

      - name: Execute Common Docker Steps
        uses: Sansen-Shimizu/common-actions/./docker@v1
        with:
          docker_username: ${{ env.DOCKER_USERNAME }}
          docker_password: ${{ env.DOCKER_PASSWORD }}
          dockerfile: Dockerfile.production
          project: isf
          repository: frontend
          tag_version: latest-dev
          cache: false
